const ENVIRONMENTS_OPTIONS = {
  PRODUCTION: "production",
  DEVELOPMENT: "development",
};

export const CURRENT_ENVIRONMENT =
  ENVIRONMENTS_OPTIONS[process.env.ENVIRONMENT] ||
  ENVIRONMENTS_OPTIONS.DEVELOPMENT;

export const isProduction = () =>
  CURRENT_ENVIRONMENT === ENVIRONMENTS_OPTIONS.PRODUCTION;
